### ISSUE TITLE
Delete dashboard need to pass grafana folder

### ISSUE THREAD

**Issue by juztas** [esnet/sense-rtmon#136]
@juztas 
```bahs
T2_US_Caltech_Test:sandie-1.ultralight.org', 'vlan': 'vlan.3601'}], 'Vlan': '3601', 'Mac': '4c:76:25:e8:44:c2', 'Name': 'hundredGigE 1/10'}, {'Site': 'urn:ogf:network:ultralight.org:2013', 'IPv6': '?port_ipv6?', 'Port': 'urn:ogf:network:ultralight.org:2013:dellos9_s0:Port-channel_103', 'IPv4': '?port_ipv4?', 'Node': 'T2_US_Caltech_Test:dellos9_s0', 'Peer': 'urn:ogf:network:tier2.ultralight.org:2024:dellos10_s0:Port-channel_101', 'Vlan': '3601', 'Mac': '4c:76:25:e8:44:c2', 'Name': 'Port-channel 103'}, {'Site': 'urn:ogf:network:sense-oasis-nrp-nautilus.io:2020', 'IPv6': '?port_ipv6?', 'Port': 'urn:ogf:network:sense-oasis-nrp-nautilus.io:2020:oasis:Pc502', 'IPv4': '?port_ipv4?', 'Node': 'T2_US_UCSD_OASIS:oasis', 'Peer': 'urn:ogf:network:sc-test.cenic.net:2020:aristaeos_s0:Port-Channel502', 'Vlan': '3601', 'Mac': '?port_mac?', 'Name': 'Pc502'}, {'Site': 'urn:ogf:network:sense-oasis-nrp-nautilus.io:2020', 'IPv6': '?port_ipv6?', 'Port': 'urn:ogf:network:sense-oasis-nrp-nautilus.io:2020:oasis:Pc500', 'IPv4': '?port_ipv4?', 'Node': 'T2_US_UCSD_OASIS:oasis', 'Peer': 'urn:ogf:network:nrp-nautilus.io:2020:edgecore_s0:PortChannel500', 'Vlan': '3601', 'Mac': '?port_mac?', 'Name': 'Pc500'}]}, 'dashbInfo': {'uid': '593b0eb9-f5bf-868b-9ed3-ec76ca995613', 'annotation_panels': [306, 307, 308, 409, 410, 411, 512, 513, 514, 615, 616, 617, 718, 719, 720, 821, 822, 823, 924, 925, 926, 1034, 1035, 1036, 1037, 1038, 1039, 1040]}, 'retries': 0}
Mon, 28 Oct 2024 03:37:19.528 - RTMonLibs.LogLib - INFO - Deleting Dashboard: RTMON-Caltech-SDSC-v2|Flow: 7fdaf618-b3e6-4f5b-864e-acaa7e456362|2024/10/22 16:12:00 (Sunami-Prod)
Traceback (most recent call last):
  File "src/python/RTMon/worker.py", line 271, in <module>
    worker.startwork()
  File "src/python/RTMon/worker.py", line 230, in startwork
    self._startwork()
  File "src/python/RTMon/worker.py", line 253, in _startwork
    self.main()
  File "src/python/RTMon/worker.py", line 219, in main
    self.delete_exe(filename, fout)
  File "src/python/RTMon/worker.py", line 104, in delete_exe
    self.g_deleteDashboard(dashbName)
TypeError: g_deleteDashboard() missing 1 required positional argument: 'folderTitle'

```

https://github.com/esnet/sense-rtmon/blob/96b33b3f3a7d493e9b456f817edb8a5a027c70b3/autogole-api/src/python/RTMon/worker.py#L98

i think it need 2 arguments:

definition: https://github.com/esnet/sense-rtmon/blob/96b33b3f3a7d493e9b456f817edb8a5a027c70b3/autogole-api/src/python/RTMonLibs/GrafanaAPI.py#L87

_Originally posted by @sunami09 in https://github.com/esnet/sense-rtmon/issues/127#issuecomment-2440606235_

**Comment by juztas** [comment]
https://github.com/esnet/sense-rtmon/pull/137
