### ISSUE TITLE
Add Mainloop to `docker-stack.yml`

### ISSUE THREAD

**Issue by sunami09** [esnet/sense-rtmon#81]

**Comment by xi-yang** [comment]
With the latest code 16e6394a3fc9a4dfd5493e89f57d8572d70ed189, the maintop got started butI still saw the below error in maintop log. @sunami09 

```
Parsing config file...

 Config file /app/config_flow/flow.yaml

Traceback (most recent call last):
  File "./se_config/generate_script.py", line 171, in <module>
    main()
  File "./se_config/generate_script.py", line 142, in main
    with open(f"level2/{data['flow']}.sh", 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'level2/rtmon-3620ddea-8e53-475b-afc1-d30b5a07d2b0.sh'
chmod: cannot access 'level2/rtmon-3620ddea-8e53-475b-afc1-d30b5a07d2b0.sh': No such file or directory
sh: 1: level2/rtmon-3620ddea-8e53-475b-afc1-d30b5a07d2b0.sh: not found


```

**Comment by sunami09** [comment]
Needs update from sense `sense-mon` because we are not getting this error in `ec2-user ` or `dev2`.

**Comment by sunami09** [comment]
@xi-yang  we can close this now right?
